sonar.projectKey=patil-rushikesh_SmartCanteenFrontend
sonar.organization=patil-rushikesh
sonar.sources=.
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/generated/**,**/.terraform/**,coverage/**,tests/**,infra/tests/**,Backend/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
